name: Kong Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'kong/specs/**'

env:
  KONG_ADMIN_URL: http://34.55.116.90:8001

jobs:
  validate-and-prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install deck
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.16.1/deck_1.16.1_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz
          sudo mv deck /usr/local/bin/

      - name: Ping Kong
        run: |
          response=$(curl -s $KONG_ADMIN_URL/status)
          if [ $? -ne 0 ]; then
            echo "Failed to ping Kong instance"
            exit 1
          fi
          echo "Kong instance is healthy"

      - name: Convert Swagger to Declarative
        run: |
          deck convert --from kong/specs/profile_swagger_v1.0.yaml --to kong/declarative/profilebuilder.yml
          if [ $? -ne 0 ]; then
            echo "Failed to convert swagger to declarative format"
            exit 1
          fi

      - name: Deck Diff
        run: |
          deck diff --state kong/declarative/profilebuilder.yml --kong-addr $KONG_ADMIN_URL
          if [ $? -ne 0 ]; then
            echo "Deck diff shows conflicts or errors"
            exit 1
          fi

      - name: Upload Declarative Config
        uses: actions/upload-artifact@v3
        with:
          name: kong-config
          path: kong/declarative/profilebuilder.yml

  deploy:
    needs: validate-and-prepare
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ env.KONG_ADMIN_URL }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Declarative Config
        uses: actions/download-artifact@v3
        with:
          name: kong-config
          path: kong/declarative

      - name: List downloaded files
        run: ls -R kong/declarative

      - name: Install deck
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.16.1/deck_1.16.1_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz
          sudo mv deck /usr/local/bin/

      - name: Deploy to Kong
        run: |
          deck sync --state kong/declarative/profilebuilder.yml --kong-addr $KONG_ADMIN_URL --select-tag profilebuilder
          if [ $? -ne 0 ]; then
            echo "Failed to sync configuration with Kong"
            exit 1
          fi
          echo "Successfully deployed to Kong"
